# Generated by Django 4.1 on 2024-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("summary", models.TextField(max_length=2000)),
                ("degree", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("previous_work", models.TextField(max_length=500)),
                ("skills", models.TextField(max_length=500)),
            ],
        ),
    ]
